### ISSUE TITLE
Missing GlobalSuppressions.cs

### ISSUE THREAD

**Issue by MasterDataBase** [insideGen/Loupedeck-Discord-OpenPlugin#1]
Hi! 
I download the project to try to add learn more about the code, but if I try to build it localy, I got an error for GlobalSuppressions.cs not present in the project folder under scr/DiscordPlugin.
Is a missing file or I missed something?

**Comment by MasterDataBase** [comment]
Meanwhile, great plugin!

**Comment by insideGen** [comment]
Thank you for your feedback.
This problem is solved with the commit [6d5633d](https://github.com/insideGen/Loupedeck-Discord-OpenPlugin/commit/6d5633de74befb4a7a1f07019884524a7a35a6ad).
